package web

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"testing"
	"time"
)

// okHandler is the protected downstream: 200 "ok" when reached.
var okHandler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte("ok"))
})

func TestMiddlewareDisabledPassesThrough(t *testing.T) {
	var a *Auth // nil => disabled
	h := a.Middleware(okHandler)

	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, httptest.NewRequest(http.MethodGet, "/anything", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("disabled auth: code = %d, want 200", rec.Code)
	}
}

// login performs POST /api/login and returns the recorder.
func login(t *testing.T, a *Auth, password string) *httptest.ResponseRecorder {
	t.Helper()
	body := `{"password":` + strconv.Quote(password) + `}`
	req := httptest.NewRequest(http.MethodPost, "/api/login", strings.NewReader(body))
	req.RemoteAddr = "10.0.0.1:1234"
	rec := httptest.NewRecorder()
	a.LoginHandler(rec, req)
	return rec
}

func TestLoginCookieRoundtrip(t *testing.T) {
	a := NewAuth("admin", "hunter2", "stable-secret", "tok")
	rec := login(t, a, "hunter2")
	if rec.Code != http.StatusNoContent {
		t.Fatalf("login: code = %d, want 204", rec.Code)
	}
	cookies := rec.Result().Cookies()
	var session *http.Cookie
	for _, c := range cookies {
		if c.Name == sessionCookieName {
			session = c
		}
	}
	if session == nil {
		t.Fatal("no session cookie set")
	}
	if !session.HttpOnly || session.SameSite != http.SameSiteLaxMode || session.Path != "/" {
		t.Errorf("cookie attrs wrong: %+v", session)
	}

	// Cookie should now pass the middleware.
	req := httptest.NewRequest(http.MethodGet, "/api/state/runs", nil)
	req.AddCookie(session)
	got := httptest.NewRecorder()
	a.Middleware(okHandler).ServeHTTP(got, req)
	if got.Code != http.StatusOK {
		t.Fatalf("valid cookie rejected: code = %d", got.Code)
	}
}

func TestLoginBadPassword(t *testing.T) {
	a := NewAuth("admin", "hunter2", "secret", "tok")
	rec := login(t, a, "wrong")
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("bad password: code = %d, want 401", rec.Code)
	}
	if len(rec.Result().Cookies()) != 0 {
		t.Error("no cookie should be set on failed login")
	}
}

func TestMiddlewareBlocksWithoutCookie(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "tok")

	req := httptest.NewRequest(http.MethodGet, "/api/state/runs", nil)
	rec := httptest.NewRecorder()
	a.Middleware(okHandler).ServeHTTP(rec, req)
	if rec.Code != http.StatusUnauthorized {
		t.Fatalf("code = %d, want 401", rec.Code)
	}
	var body map[string]string
	if err := json.NewDecoder(rec.Body).Decode(&body); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if body["error"] != "unauthorized" {
		t.Errorf("body = %v, want error:unauthorized", body)
	}

	// SPA shell GETs pass without a session — the bundle carries no run
	// data and the browser needs it to render the login screen at all.
	req2 := httptest.NewRequest(http.MethodGet, "/runs", nil)
	rec2 := httptest.NewRecorder()
	a.Middleware(okHandler).ServeHTTP(rec2, req2)
	if rec2.Code != http.StatusOK {
		t.Fatalf("SPA shell GET = %d, want 200 (must render login screen)", rec2.Code)
	}

	// Non-GET on a non-API path is still gated (bare 401, no JSON body).
	req3 := httptest.NewRequest(http.MethodPost, "/runs", nil)
	rec3 := httptest.NewRecorder()
	a.Middleware(okHandler).ServeHTTP(rec3, req3)
	if rec3.Code != http.StatusUnauthorized {
		t.Fatalf("non-api POST code = %d, want 401", rec3.Code)
	}
	if rec3.Body.Len() != 0 {
		t.Errorf("non-api 401 should have empty body, got %q", rec3.Body.String())
	}
}

func TestIngestBearer(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "secret-token")
	h := a.Middleware(okHandler)

	// Correct bearer passes.
	req := httptest.NewRequest(http.MethodPost, "/ingest", strings.NewReader("{}"))
	req.Header.Set("Authorization", "Bearer secret-token")
	rec := httptest.NewRecorder()
	h.ServeHTTP(rec, req)
	if rec.Code != http.StatusOK {
		t.Fatalf("valid bearer: code = %d, want 200", rec.Code)
	}

	// Wrong bearer blocked.
	req2 := httptest.NewRequest(http.MethodPost, "/ingest", strings.NewReader("{}"))
	req2.Header.Set("Authorization", "Bearer nope")
	rec2 := httptest.NewRecorder()
	h.ServeHTTP(rec2, req2)
	if rec2.Code != http.StatusUnauthorized {
		t.Fatalf("wrong bearer: code = %d, want 401", rec2.Code)
	}

	// Missing bearer blocked.
	req3 := httptest.NewRequest(http.MethodPost, "/ingest", strings.NewReader("{}"))
	rec3 := httptest.NewRecorder()
	h.ServeHTTP(rec3, req3)
	if rec3.Code != http.StatusUnauthorized {
		t.Fatalf("missing bearer: code = %d, want 401", rec3.Code)
	}
}

func TestIngestTokenAutoGenerated(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "")
	if a.IngestToken() == "" {
		t.Fatal("auto-generated ingest token should be non-empty")
	}
	if len(a.IngestToken()) < 32 {
		t.Errorf("token too short: %q", a.IngestToken())
	}
}

func TestEphemeralSessionKey(t *testing.T) {
	if !NewAuth("u", "p", "", "t").EphemeralSessionKey() {
		t.Error("empty secret should mark ephemeral")
	}
	if NewAuth("u", "p", "s", "t").EphemeralSessionKey() {
		t.Error("stable secret should not be ephemeral")
	}
}

func TestRateLimitTrips(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "tok")
	// 5 attempts/min allowed; 6th trips regardless of correctness.
	for i := 0; i < 5; i++ {
		rec := login(t, a, "wrong")
		if rec.Code != http.StatusUnauthorized {
			t.Fatalf("attempt %d: code = %d, want 401", i, rec.Code)
		}
	}
	rec := login(t, a, "wrong")
	if rec.Code != http.StatusTooManyRequests {
		t.Fatalf("6th attempt: code = %d, want 429", rec.Code)
	}
}

func TestRateLimitPerIP(t *testing.T) {
	rl := newRateLimiter(2, time.Minute)
	for i := 0; i < 2; i++ {
		if !rl.allow("a") {
			t.Fatalf("ip a attempt %d should be allowed", i)
		}
	}
	if rl.allow("a") {
		t.Fatal("ip a 3rd should be blocked")
	}
	if !rl.allow("b") {
		t.Fatal("ip b should have its own window")
	}
}

func TestMeHandlerNilReceiver(t *testing.T) {
	var a *Auth
	rec := httptest.NewRecorder()
	a.MeHandler(rec, httptest.NewRequest(http.MethodGet, "/api/me", nil))
	if rec.Code != http.StatusOK {
		t.Fatalf("code = %d, want 200", rec.Code)
	}
	var resp meResponse
	if err := json.NewDecoder(rec.Body).Decode(&resp); err != nil {
		t.Fatalf("decode: %v", err)
	}
	if resp.AuthEnabled {
		t.Error("auth_enabled should be false for nil receiver")
	}
	if !resp.Authenticated {
		t.Error("authenticated should be true when auth disabled")
	}
}

func TestMeHandlerEnabled(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "tok")

	// Unauthenticated.
	rec := httptest.NewRecorder()
	a.MeHandler(rec, httptest.NewRequest(http.MethodGet, "/api/me", nil))
	var resp meResponse
	_ = json.NewDecoder(rec.Body).Decode(&resp)
	if !resp.AuthEnabled || resp.Authenticated {
		t.Errorf("unauth: %+v, want enabled:true authenticated:false", resp)
	}

	// Authenticated via cookie.
	loginRec := login(t, a, "pw")
	var session *http.Cookie
	for _, c := range loginRec.Result().Cookies() {
		if c.Name == sessionCookieName {
			session = c
		}
	}
	req := httptest.NewRequest(http.MethodGet, "/api/me", nil)
	req.AddCookie(session)
	rec2 := httptest.NewRecorder()
	a.MeHandler(rec2, req)
	var resp2 meResponse
	_ = json.NewDecoder(rec2.Body).Decode(&resp2)
	if !resp2.Authenticated || resp2.Username != "admin" {
		t.Errorf("auth: %+v, want authenticated:true username:admin", resp2)
	}
}

func TestLogoutClearsCookie(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "tok")
	rec := httptest.NewRecorder()
	a.LogoutHandler(rec, httptest.NewRequest(http.MethodPost, "/api/logout", nil))
	if rec.Code != http.StatusNoContent {
		t.Fatalf("code = %d, want 204", rec.Code)
	}
	var session *http.Cookie
	for _, c := range rec.Result().Cookies() {
		if c.Name == sessionCookieName {
			session = c
		}
	}
	if session == nil {
		t.Fatal("logout should set an (expiring) session cookie")
	}
	if session.Value != "" || !session.Expires.Before(time.Now()) {
		t.Errorf("logout cookie not expired: %+v", session)
	}
}

func TestTamperedCookieRejected(t *testing.T) {
	a := NewAuth("admin", "pw", "secret", "tok")
	if a.validSession("v1:9999999999:deadbeef") {
		t.Error("forged HMAC should be rejected")
	}
	if a.validSession("v1:1:" + a.mac("1")) {
		t.Error("expired session should be rejected")
	}
	if a.validSession("garbage") {
		t.Error("malformed value should be rejected")
	}
}
