package looper

import (
	"bytes"
	"encoding/json"
	"fmt"

	jsonschema "github.com/santhosh-tekuri/jsonschema/v6"

	"github.com/cuatroochenta-idi/looper-agent/loop"
	"github.com/cuatroochenta-idi/looper-agent/tool"
)

// WithStructuredOutput configures the agent to emit JSON matching the
// shape of type T on its final turn. The framework generates the JSON
// Schema from T (using the same jsonschema struct tags tools use), then
// injects an implicit final_response tool whose schema matches T plus a
// system-prompt instruction requiring the model to call it.
//
// res.Output ends up as a JSON string; pass it through Decode[T] to
// unmarshal into a typed Go value:
//
//	type Result struct { Score float64 `json:"score"` }
//	agent := looper.MustNewAgent(p, sysPrompt, looper.WithStructuredOutput[Result]())
//	res, _ := agent.Run(ctx, "score this")
//	var out Result
//	_ = looper.Decode(res, &out)
//
// Schema generation reuses the same code path as tool inputs so all the
// strict-mode invariants (additionalProperties:false, required propagation,
// time.Time → date-time, etc.) apply here too.
//
// Panics if T's schema can't be generated — that's a programmer error
// caught at agent construction, not a runtime concern.
func WithStructuredOutput[T any]() AgentOption {
	var zero T
	schema, err := tool.GenerateSchema(zero)
	if err != nil {
		panic(fmt.Sprintf("WithStructuredOutput: generate schema for %T: %v", zero, err))
	}
	return func(a *Agent) {
		a.structuredOutputSchema = schema
	}
}

// WithOutputRetries enables automatic re-prompting when the model's
// structured-output payload doesn't validate against T's schema (or a
// custom WithOutputValidator returns an error). After each rejection
// the framework appends the validator's message as a system hint and
// asks the model to try again, up to n retries. Exhausting the budget
// terminates the run with Status="output_validation_exhausted" and the
// last attempted JSON preserved on res.Output.
//
// Zero (the default) keeps the legacy behaviour — the first JSON the
// model emits is accepted as-is.
func WithOutputRetries(n int) AgentOption {
	return func(a *Agent) {
		a.outputMaxRetries = n
	}
}

// WithOutputValidator adds a typed business-rule validator that runs
// AFTER the JSON Schema check passes. Return any error to reject the
// payload; the framework forwards the error message to the model as
// the next-turn hint. Pair with WithOutputRetries to enable retries.
//
// Use ErrOutputInvalid for a clean, intent-revealing rejection reason.
func WithOutputValidator[T any](fn func(T) error) AgentOption {
	return func(a *Agent) {
		a.outputCustomValidator = func(raw []byte) error {
			var v T
			if err := json.Unmarshal(raw, &v); err != nil {
				return fmt.Errorf("invalid JSON for validator: %w", err)
			}
			return fn(v)
		}
	}
}

// ErrOutputInvalid wraps a human-readable rejection reason. Intended as
// the return value from a WithOutputValidator function — the framework
// surfaces the message verbatim to the model on the next turn.
//
// Mirrors tool.RejectWithHint so the two declarative-validation paths
// (tool input pre-execute, structured output) feel symmetric.
func ErrOutputInvalid(reason string) error {
	return fmt.Errorf("%s", reason)
}

// Decode unmarshals res.Output into out as JSON. Use after a run that
// configured WithStructuredOutput so the output is a JSON object matching
// the requested type. Returns a clear error when res is nil or the output
// is not valid JSON for T.
func Decode[T any](res *RunResult, out *T) error {
	if res == nil {
		return fmt.Errorf("looper.Decode: nil RunResult")
	}
	if out == nil {
		return fmt.Errorf("looper.Decode: nil destination")
	}
	if res.Output == "" {
		return fmt.Errorf("looper.Decode: empty output (status=%q)", res.Status)
	}
	if err := json.Unmarshal([]byte(res.Output), out); err != nil {
		return fmt.Errorf("looper.Decode: %w (output=%q)", err, res.Output)
	}
	return nil
}

// applyStructuredOutputOption wires schema + validation into the loop.
// Called by NewAgent after the agent options have run. When output
// retries are configured we additionally compile the schema and pass
// the validator + custom validator down so the loop can re-prompt the
// model on schema-incompatible payloads.
func applyStructuredOutputOption(a *Agent, opts *[]loop.LoopOption) {
	if len(a.structuredOutputSchema) == 0 {
		return
	}
	*opts = append(*opts, loop.WithLoopStructuredOutput(a.structuredOutputSchema))

	if a.outputMaxRetries <= 0 && a.outputCustomValidator == nil {
		return
	}
	compiled, err := tool.CompileSchema("structured-output", a.structuredOutputSchema)
	if err != nil {
		// Internal schema generated by us — failure here means the
		// framework is broken, not the caller's fault. Panic preserves
		// the diagnostic and matches MustNewTool's contract.
		panic(fmt.Sprintf("looper: compile output schema: %v", err))
	}
	schemaValidator := func(raw []byte) error {
		parsed, err := jsonschemaUnmarshal(raw)
		if err != nil {
			return err
		}
		return compiled.Validate(parsed)
	}
	*opts = append(*opts, loop.WithLoopOutputValidation(
		schemaValidator,
		a.outputMaxRetries,
		a.outputCustomValidator,
	))
}

// jsonschemaUnmarshal mirrors the parse step inside tool.Validate so the
// numeric-precision semantics stay consistent (santhosh-tekuri/jsonschema
// expects a json.Number-preserving unmarshal for int / float range checks).
func jsonschemaUnmarshal(raw []byte) (any, error) {
	return jsonschema.UnmarshalJSON(bytes.NewReader(raw))
}
